# Generated by Django 2.1.7 on 2019-02-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('post_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('num_spots', models.IntegerField()),
                ('price_per_spot', models.DecimalField(decimal_places=2, max_digits=6)),
                ('winning_spot', models.IntegerField()),
                ('num_spots_for_winner', models.IntegerField()),
                ('datetime_posted', models.DateTimeField()),
                ('datetime_completed', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpotCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=10)),
                ('num_spots', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='spotcount',
            unique_together={('post_id', 'num_spots')},
        ),
    ]
